/** Paths blocked on the public marketing host (www). Allow everything else via `Allow: /`. */
export const MARKETING_ROBOTS_DISALLOW = [
    "/api/",
    "/_next/",
    "/favicon_io/",
    "/growth",
    "/growth/",
    "/onboarding",
    "/onboarding/",
    "/newsletter",
    "/newsletter/",
    "/dashboard",
    "/dashboard/",
    "/settings",
    "/settings/",
    "/businesses",
    "/businesses/",
    "/reviews",
    "/reviews/",
    "/campaigns",
    "/campaigns/",
    "/analytics",
    "/analytics/",
    "/competitors",
    "/competitors/",
    "/customers",
    "/customers/",
    "/review-requests",
    "/review-requests/",
    "/requests",
    "/requests/",
    "/questions",
    "/questions/",
    "/google-seo-aeo",
    "/google-seo-aeo/",
    "/login",
    "/signup",
    "/forgot-password",
    "/reset-password",
    "/r/",
    "/w/",
] as const;

export const AI_CRAWLER_ALLOW = ["/", "/about", "/blog", "/docs", "/help", "/privacy", "/terms", "/pricing"] as const;

export const AI_CRAWLER_DISALLOW = [
    "/api/",
    "/growth",
    "/onboarding",
    "/newsletter",
    "/dashboard",
    "/customers",
    "/r/",
    "/w/",
    "/login",
    "/signup",
] as const;
