export const OAUTH_GBP_CATEGORY_MAP: Record<string, string> = {
    restaurant: "restaurant",
    dining: "restaurant",
    food: "restaurant",
    eatery: "restaurant",
    pizza: "restaurant",
    sushi: "restaurant",
    burger: "restaurant",
    grill: "restaurant",
    bistro: "restaurant",
    steakhouse: "restaurant",
    bakery: "restaurant",
    cafe: "coffee",
    coffee: "coffee",
    "coffee shop": "coffee",
    tea: "coffee",
    salon: "salon",
    beauty: "salon",
    barber: "salon",
    "hair salon": "salon",
    "nail salon": "salon",
    cosmetics: "salon",
    dentist: "dental",
    dental: "dental",
    orthodontist: "dental",
    gym: "gym",
    fitness: "gym",
    "yoga studio": "gym",
    "pilates studio": "gym",
    "personal trainer": "gym",
    crossfit: "gym",
    spa: "spa",
    massage: "spa",
    wellness: "spa",
    hotel: "hotel",
    motel: "hotel",
    resort: "hotel",
    inn: "hotel",
    "bed and breakfast": "hotel",
    retail: "retail",
    store: "retail",
    shop: "retail",
    boutique: "retail",
    market: "retail",
    auto: "automotive",
    automotive: "automotive",
    "car dealer": "automotive",
    "car repair": "automotive",
    mechanic: "automotive",
    "auto repair": "automotive",
    doctor: "healthcare",
    hospital: "healthcare",
    clinic: "healthcare",
    medical: "healthcare",
    healthcare: "healthcare",
    pharmacy: "healthcare",
    veterinarian: "healthcare",
    chiropractor: "healthcare",
};
