/**
 * Blog posts — Month 2 (posts 5–8).
 * Response Templates + Local SEO.
 */

import type { BlogPost } from "./blog-types";

export const post5: BlogPost = {
    slug: "how-to-respond-to-a-1-star-review",
    title: "How to Respond to a 1-Star Review (With 5 Real Templates)",
    excerpt: "A bad review isn't a crisis — it's an opportunity. Here's the 5-step framework and 5 real response templates for turning a 1-star review into a trust builder.",
    pillar: "responding-to-reviews",
    pillarLabel: "Responding to Reviews",
    publishedAt: "2026-04-07",
    readMinutes: 8,
    author: { name: "Zyene Team", role: "Growth & SEO" },
    metaTitle: "How to Respond to a 1-Star Google Review (5 Templates) — Zyene Reviews",
    metaDescription: "Proven 5-step framework and 5 ready-to-use templates for responding to 1-star Google reviews. Turn bad reviews into trust signals for new customers.",
    keywords: ["how to respond to a 1 star review", "respond to negative review", "bad google review response", "1 star review template", "negative review response"],
    relatedSlugs: ["ai-reply-mistakes-to-avoid", "why-google-reviews-matter-in-2026"],
    internalLinks: [
        { label: "See how Zyene's AI replies work", href: "/features" },
        { label: "Check out our negative review response template library", href: "/resources/negative-review-templates" },
    ],
    body: [
        { type: "p", text: "A 1-star review lands in your inbox and your stomach drops. Your first instinct might be to ignore it, argue with it, or delete your account entirely. All of these are the wrong move." },
        { type: "p", text: "Here's the counterintuitive truth: a well-handled 1-star review with a thoughtful response can be more valuable to your reputation than five 5-star reviews with no response. Potential customers read 1-star reviews specifically to see how you handle adversity." },
        { type: "h2", text: "Why Your Response Matters More Than the Review" },
        { type: "p", text: "When someone is deciding whether to visit your business, a negative review with a response like 'We're so sorry you had this experience, John. We've addressed this with our team and would love to make it right — please email us at [address]' communicates several things simultaneously: you're listening, you take feedback seriously, you act on it, and you're professional under pressure." },
        { type: "p", text: "Reviews without responses signal the opposite: that you don't care, you're not paying attention, or you have something to hide. 53% of consumers expect a business to respond to reviews within a week. When you don't, they notice." },
        { type: "h2", text: "The 5-Step Response Framework" },
        { type: "ol", items: [
            "Acknowledge: Start by acknowledging the customer's experience without getting defensive. Use their name if visible in the review.",
            "Apologize: Express genuine regret — not necessarily for wrongdoing, but for the fact that their experience didn't meet expectations. 'We're sorry your visit didn't go as expected' works even when the complaint is unfair.",
            "Take responsibility (where appropriate): If a mistake was made, own it briefly and specifically. Don't be vague — 'the wait time was unacceptable on that day' is better than 'sometimes things don't go as planned'.",
            "Offer resolution: Always offer to make it right. Give them a direct contact method — an email address or phone number — so the conversation can continue privately. Never negotiate publicly.",
            "Close gracefully: End with an invitation to return, a commitment to do better, or a direct thank-you for the feedback. Keep it professional and human.",
        ]},
        { type: "h2", text: "Template 1: Service Quality Complaint" },
        { type: "quote", text: "Hi [Name], thank you for taking the time to leave this feedback. We're genuinely sorry your experience didn't reflect the quality we work hard to deliver. What you described is not the standard we hold ourselves to, and I've shared your feedback directly with our team. We'd love the opportunity to make this right — please email us at [email] and we'll take care of you. Thank you again for letting us know." },
        { type: "h2", text: "Template 2: Wait Time / Speed Complaint" },
        { type: "quote", text: "Hi [Name], we're sorry the wait time on your visit was longer than expected — we know your time is valuable. [Day/time] can be unexpectedly busy for us, and we clearly fell short of managing it well that day. We're working on [specific improvement, e.g., staffing, process]. We'd love to earn your business back — please reach out to [email] and we'll make your next visit right." },
        { type: "h2", text: "Template 3: Billing or Pricing Dispute" },
        { type: "quote", text: "Hi [Name], thank you for sharing this. We never want a customer to feel surprised or unfairly charged, and I'm sorry this was your experience. Billing details vary by situation, and I'd like to understand yours specifically. Please reach out to us at [email] or call [phone] and ask for [manager name] — I'll personally review your account and make sure we get this resolved. Thank you for giving us the chance to address it." },
        { type: "h2", text: "Template 4: Rude Staff Complaint" },
        { type: "quote", text: "Hi [Name], we take feedback about our team's conduct seriously, and I'm sorry your interaction fell short of the warm, professional experience we work to provide. I've shared your review with our management team. We'd be grateful for the chance to learn more about what happened — please reach out at [email]. Your feedback helps us improve, and we appreciate you taking the time to share it." },
        { type: "h2", text: "Template 5: Vague or Unclear Complaint" },
        { type: "quote", text: "Hi [Name], we're sorry to see you had a disappointing experience. We'd genuinely like to understand what happened so we can make it right. Please reach out to us at [email] — we'd love to speak with you directly and address your concerns. Thank you for letting us know." },
        { type: "h2", text: "What NOT to Do" },
        { type: "ul", items: [
            "Don't argue: Even if the reviewer is factually wrong, a public argument makes you look worse than the original review. Never debate the details publicly.",
            "Don't offer refunds publicly: Offering compensation in a public response invites review fraud. Handle it privately.",
            "Don't use the same template for every review: Reviewers and potential customers can tell. Specific, personal responses are far more effective.",
            "Don't wait: Respond within 24–48 hours. The longer you wait, the more people see an unanswered negative review.",
            "Don't write a novel: Keep responses to 3–5 sentences. Overly long responses look defensive.",
        ]},
        { type: "tip", text: "Using AI tools like Zyene's reply suggestions can give you a well-structured starting point for each response that you then personalize. The key word is personalize — always edit the AI draft to include specific details from the review." },
        { type: "cta", ctaLabel: "Get 20+ response templates in our free template library →", ctaHref: "/resources/negative-review-templates" },
    ],
};

export const post6: BlogPost = {
    slug: "ai-reply-mistakes-to-avoid",
    title: "5 AI Reply Mistakes to Avoid When Responding to Reviews",
    excerpt: "AI reply tools can save hours every week — but only if you use them correctly. These 5 mistakes will make your AI responses hurt your reputation instead of helping it.",
    pillar: "responding-to-reviews",
    pillarLabel: "Responding to Reviews",
    publishedAt: "2026-04-14",
    readMinutes: 6,
    author: { name: "Zyene Team", role: "Growth & SEO" },
    metaTitle: "5 AI Reply Mistakes to Avoid for Google Reviews — Zyene Reviews",
    metaDescription: "Using AI to respond to reviews? Avoid these 5 common mistakes that make AI replies backfire. Learn how to use AI reply tools correctly for Google reviews.",
    keywords: ["ai reply mistakes", "ai review responses", "ai google review reply", "how to respond to reviews with ai", "review response ai tips"],
    relatedSlugs: ["how-to-respond-to-a-1-star-review", "why-google-reviews-matter-in-2026"],
    internalLinks: [
        { label: "Try Zyene's AI reply feature", href: "/features" },
    ],
    body: [
        { type: "p", text: "AI tools for review responses are a genuine productivity breakthrough. The ability to generate a professional, well-structured reply to any review in seconds — rather than spending 5–10 minutes per response — can save a business owner several hours every week." },
        { type: "p", text: "But AI replies done wrong can actively damage your reputation. Here are the 5 mistakes we see most often, and exactly how to avoid each one." },
        { type: "h2", text: "Mistake 1: Publishing AI Replies Without Editing" },
        { type: "p", text: "This is the most common and most damaging mistake. AI models generate grammatically correct, professionally-toned responses — but they don't know your customer, your business, or the specific context of the review." },
        { type: "p", text: "A response to 'Great burger!' that says 'Thank you for visiting [Business Name]! We're delighted you enjoyed your experience with our culinary offerings and look forward to welcoming you again!' sounds robotic and generic. Regulars will notice. New visitors will notice." },
        { type: "tip", text: "Treat AI replies as first drafts, never final drafts. Always add at least one specific detail from the review (the dish they mentioned, the service they praised, the staff member they named) before publishing." },
        { type: "h2", text: "Mistake 2: Using the Same Opening Phrase for Every Review" },
        { type: "p", text: "AI models default to predictable opening phrases: 'Thank you for your wonderful review!', 'We're so glad you enjoyed your visit!', 'We appreciate you taking the time to share your feedback!'. When all 50 of your recent review responses start with the same sentence, it's a clear signal — to both customers and Google — that no human is actually reading or responding." },
        { type: "ul", items: [
            "✗ 'Thank you for your wonderful review!' (used 47 times)",
            "✓ 'Great to hear about the tacos, Maria — our kitchen team will love this.'",
            "✓ 'Thanks, James! The Friday night crowd does move fast, so glad we could still take care of you.'",
        ]},
        { type: "h2", text: "Mistake 3: Ignoring 3-Star Reviews" },
        { type: "p", text: "Most businesses focus their review response energy on the extremes — effusively thanking 5-star reviewers and carefully managing 1-star ones. But 3-star reviews are where the real conversion opportunity lives." },
        { type: "p", text: "A 3-star review means a customer had a mixed experience — good enough to come back, but not good enough to recommend. A thoughtful, specific response to a 3-star review that addresses what went wrong and invites them back converts 'meh' customers into loyal advocates more often than any other response type." },
        { type: "h2", text: "Mistake 4: Defensive Responses to Negative Reviews" },
        { type: "p", text: "AI models, when prompted with a negative review, sometimes generate responses that subtly dispute the reviewer's characterization. 'While we always strive for excellence...' or 'Our team works hard to ensure...' can read as deflection rather than accountability." },
        { type: "p", text: "Before publishing any AI-generated response to a negative review, read it from the perspective of a potential customer who is reading it to see how you handle criticism. Does it sound defensive? Does it focus more on your reputation than the customer's experience? If yes, edit it." },
        { type: "h2", text: "Mistake 5: Not Using Responses to Mention Key Services" },
        { type: "p", text: "Google's algorithm for local search reads and indexes the content of your review responses. This means your responses are an opportunity to naturally mention your services, location, and specialties in a way that improves your keyword relevance." },
        { type: "p", text: "A response like 'We're so glad you enjoyed the deep cleaning at our Seattle dental practice — our hygiene team will be thrilled to hear this!' is better for both the reviewer and for local SEO than 'Thanks for the 5 stars!'" },
        { type: "warning", text: "Don't stuff keywords into review responses. Natural mentions of your services and location are beneficial. 'Dentist Seattle deep cleaning affordable family dental' in a response will look like spam and could have the opposite effect." },
        { type: "h2", text: "How to Use AI Replies Correctly" },
        { type: "ol", items: [
            "Use AI to generate a structured first draft that handles tone, format, and the framework of the response.",
            "Read the original review again — look for specific details (names, items, events, emotions).",
            "Edit the AI draft to include at least 1–2 specific details from the review.",
            "Vary your opening phrase. Never use the same opener twice in a row.",
            "For negative reviews: read the final response out loud as if you're a skeptical potential customer before publishing.",
        ]},
        { type: "cta", ctaLabel: "See how Zyene's AI reply suggestions work →", ctaHref: "/features" },
    ],
};

export const post7: BlogPost = {
    slug: "google-business-profile-optimization-checklist",
    title: "Google Business Profile Optimization Checklist for 2026",
    excerpt: "A fully optimized Google Business Profile can 2–3× your local search visibility without spending anything on ads. This is the complete checklist for 2026.",
    pillar: "local-seo",
    pillarLabel: "Local SEO",
    publishedAt: "2026-04-21",
    readMinutes: 10,
    author: { name: "Zyene Team", role: "Growth & SEO" },
    metaTitle: "Google Business Profile Optimization Checklist 2026 — Zyene Reviews",
    metaDescription: "The complete Google Business Profile optimization checklist for 2026. 30+ actionable steps to rank higher in Google Maps and get more calls, clicks, and customers.",
    keywords: ["google business profile optimization", "gbp optimization checklist", "google my business optimization 2026", "how to optimize google business profile"],
    relatedSlugs: ["how-reviews-impact-local-map-pack-ranking", "why-google-reviews-matter-in-2026"],
    internalLinks: [
        { label: "See Zyene's GBP keyword tracking feature", href: "/features" },
        { label: "Try Zyene free", href: "/signup" },
    ],
    body: [
        { type: "p", text: "Your Google Business Profile (GBP) is the single most powerful free marketing tool available to local businesses. When fully optimized, it can put you in the Local 3-Pack for dozens of relevant searches, driving calls, website visits, and direction requests — without spending a dollar on ads." },
        { type: "p", text: "Most businesses have a GBP that is 40–60% complete. This checklist covers every optimization available in 2026. Work through it once, then use it for periodic audits." },
        { type: "h2", text: "Section 1: Basic Information (Foundation)" },
        { type: "ul", items: [
            "Business name: Use your exact legal/operating business name. No keyword stuffing ('Best Pizza NYC — Mario's'). Google will penalize this.",
            "Primary category: This is the most important single field in your GBP. Choose the most specific category that accurately describes your primary service.",
            "Additional categories: Add up to 9 secondary categories for related services (e.g., a restaurant that is also a 'Sports Bar' or 'Catering Food and Drink Supplier').",
            "Address: Verify your exact address is correct and matches your website, citations, and social profiles.",
            "Service area: If you serve customers at their location, add your service area radius or zip codes.",
            "Phone number: Use a local number, not a tracking number, as your primary. Add tracking numbers as secondary.",
            "Website: Link to your homepage, or a location-specific landing page for multi-location businesses.",
            "Hours: Add accurate regular hours, holiday hours, and special hours. Outdated hours are a top source of negative reviews.",
        ]},
        { type: "h2", text: "Section 2: Photos (High Impact)" },
        { type: "ul", items: [
            "Cover photo: 1080×608px minimum. Should show your storefront, interior, or primary product/service. Updated within the last year.",
            "Profile photo: Your logo, 250×250px minimum.",
            "Interior photos: At least 5–10 showing the atmosphere and space.",
            "Exterior photos: Multiple angles, including the street view so customers can find you.",
            "Team photos: Staff photos significantly increase trust and click-through rates.",
            "Product/service photos: The more specific, the better. A menu item, a before/after, a completed job.",
            "Total photo count: Aim for 30+ photos. Listings with more than 100 photos get 965% more direction requests (source: Google).",
        ]},
        { type: "tip", text: "Photo freshness matters. Add at least 1–2 new photos per month to signal to Google that your profile is actively maintained. Use a photo for every seasonal menu, promotion, or service addition." },
        { type: "h2", text: "Section 3: Services and Products" },
        { type: "ul", items: [
            "Services: Add every service you offer with individual names and descriptions. Include natural keyword language in descriptions.",
            "Products: If you sell products, add them with photos, prices, and descriptions.",
            "Menu (restaurants): Upload your full menu using Google's menu editor. Keep it current.",
            "Service descriptions: Write 2–3 sentence descriptions for each service. These are indexed by Google and can appear in search results.",
        ]},
        { type: "h2", text: "Section 4: Business Attributes" },
        { type: "ul", items: [
            "Identity attributes: Woman-owned, veteran-led, LGBTQ+ friendly — these appear as prominent labels on your profile and filter results.",
            "Accessibility: Wheelchair accessible entrance, restroom, parking — critical for certain searches.",
            "Amenities: Free WiFi, outdoor seating, in-store shopping, curbside pickup, etc.",
            "Payment methods: Accepted payment types including credit cards, NFC/contactless.",
            "Highlights: Award-winning, locally owned, established year.",
        ]},
        { type: "h2", text: "Section 5: Reviews (Most Important Long-Term Signal)" },
        { type: "ul", items: [
            "Total review count: Target 50+ reviews to enter the competitive range for local 3-pack placement.",
            "Response rate: Respond to 100% of reviews — positive and negative.",
            "Response time: Aim for under 48 hours for all reviews, under 24 hours for negative ones.",
            "Review velocity: Maintain a consistent flow of new reviews. 5–10/month is ideal for most businesses.",
            "Keyword mentions: Encourage customers to mention specific services or products in their reviews (but never dictate exact wording).",
        ]},
        { type: "h2", text: "Section 6: Q&A Section" },
        { type: "ul", items: [
            "Seed common questions: Use a secondary account or ask a team member to submit the most frequently asked questions — do you take reservations? Is there parking? Do you accept insurance?",
            "Answer all questions: As the business owner, your answers appear prominently. Use keyword-rich answers.",
            "Monitor regularly: Anyone can add questions. Check weekly and answer promptly.",
        ]},
        { type: "h2", text: "Section 7: Google Posts" },
        { type: "ul", items: [
            "Post frequency: Publish at least 1 Google Post per week. Posts expire after 7 days but contribute to profile freshness signals.",
            "Post types: What's New, Event, Offer, Product — vary your post types.",
            "Include CTAs: Every post should have a call-to-action: Learn More, Book, Order, Sign Up.",
            "Include photos: Posts with photos get significantly more clicks.",
        ]},
        { type: "h2", text: "Section 8: Messaging and Booking" },
        { type: "ul", items: [
            "Enable messaging: Turn on Google Business Messages if you have capacity to respond promptly (within 24 hours).",
            "Booking button: If you use an online booking system (Acuity, OpenTable, etc.), add the booking URL to your profile.",
            "Response commitment: Only enable messaging if you'll actually respond. Unanswered messages hurt your profile score.",
        ]},
        { type: "tip", text: "Use Zyene's GBP keyword performance dashboard to see which search queries are driving impressions and clicks to your Google Business Profile. This data shows you where to focus your optimization effort." },
        { type: "cta", ctaLabel: "Track your GBP keyword performance with Zyene →", ctaHref: "/features" },
    ],
};

export const post8: BlogPost = {
    slug: "how-reviews-impact-local-map-pack-ranking",
    title: "How Reviews Impact Your Google Local Map Pack Ranking",
    excerpt: "Reviews are one of the three core factors in Google's local ranking algorithm. Here's exactly how they affect your placement in the Local 3-Pack — and what you can do about it.",
    pillar: "local-seo",
    pillarLabel: "Local SEO",
    publishedAt: "2026-04-28",
    readMinutes: 7,
    author: { name: "Zyene Team", role: "Growth & SEO" },
    metaTitle: "How Google Reviews Impact Local Map Pack Ranking — Zyene Reviews",
    metaDescription: "Understand exactly how Google reviews affect your local map pack (3-pack) ranking. Review quantity, recency, response rate, and keyword mentions all matter.",
    keywords: ["local map pack ranking", "google reviews ranking factor", "how reviews affect local seo", "google 3 pack ranking", "reviews local search ranking"],
    relatedSlugs: ["google-business-profile-optimization-checklist", "how-to-get-50-google-reviews-in-30-days"],
    internalLinks: [
        { label: "Zyene GBP keyword tracking", href: "/features" },
        { label: "How to get more reviews fast", href: "/blog/how-to-get-50-google-reviews-in-30-days" },
    ],
    body: [
        { type: "p", text: "When someone searches 'dentist near me' or 'best pizza in Austin', Google shows a map with three business results — the Local 3-Pack. Research consistently shows that around 44% of all clicks on local search results go to these three positions." },
        { type: "p", text: "Getting into the 3-Pack is the most valuable organic marketing move most local businesses can make. And reviews are one of the three primary levers you can pull to get there." },
        { type: "h2", text: "Google's Three Local Ranking Factors" },
        { type: "p", text: "Google uses three factors to determine which businesses appear in the Local 3-Pack:" },
        { type: "ul", items: [
            "Relevance: How well your Google Business Profile matches what the user is searching for. Completeness of your GBP, accurate categories, and service descriptions all contribute.",
            "Proximity: How close your business is to the searcher's location. This is largely outside your control.",
            "Prominence: How well-known and reputable your business is — both online and offline. This is where reviews live.",
        ]},
        { type: "p", text: "Of the three, Proximity is fixed, Relevance is optimized through GBP completeness, and Prominence is built through reviews, citations, and backlinks. For most businesses, Prominence — and specifically reviews — is where the biggest ranking opportunity exists." },
        { type: "h2", text: "Review Factors That Influence Your Ranking" },
        { type: "h3", text: "1. Review Quantity" },
        { type: "p", text: "More reviews = more Prominence signal. There's a logarithmic relationship — going from 0 to 50 reviews has a much larger impact than going from 200 to 250. The biggest ranking jumps typically happen around the 20, 50, and 100 review thresholds." },
        { type: "h3", text: "2. Review Recency (Freshness)" },
        { type: "p", text: "Google weights recent reviews more heavily than older ones. A business with 50 reviews in the last 6 months will often outrank a business with 200 reviews that are mostly 3+ years old. This is why review management is an ongoing process — not a 'get to X and stop' goal." },
        { type: "tip", text: "Google's algorithm gives significantly more weight to reviews from the last 90 days. A business that consistently gets 10 new reviews per month maintains a constantly refreshing 'recency advantage' over competitors who set-and-forget their review strategy." },
        { type: "h3", text: "3. Average Star Rating" },
        { type: "p", text: "Your overall rating matters, but perhaps less than you'd expect. A 4.3-star business with 120 reviews typically outranks a 4.9-star business with 8 reviews. Quantity and recency often outweigh marginal rating differences." },
        { type: "h3", text: "4. Response Rate" },
        { type: "p", text: "Google has confirmed that businesses that respond to reviews rank higher than those that don't. Responding signals to Google that the business is actively managed — a positive signal for Prominence. Your response rate (the % of reviews you respond to) is visible in your GBP insights dashboard." },
        { type: "h3", text: "5. Keyword Mentions in Reviews" },
        { type: "p", text: "Google reads and indexes the content of reviews. When customers mention specific services, locations, or terms in reviews — 'best deep dish pizza in Wicker Park' or 'emergency HVAC repair' — those keywords contribute to your relevance for those searches. Encourage customers to be specific in their reviews, but never dictate exact wording." },
        { type: "h2", text: "What This Means in Practice" },
        { type: "table", table: {
            headers: ["Review Signal", "Impact on Ranking", "How to Improve"],
            rows: [
                ["Review quantity", "High — especially 0→50 range", "Systematic review request process"],
                ["Review recency", "High — 90-day window matters most", "Consistent monthly review collection"],
                ["Average star rating", "Medium — less than quantity/recency", "Negative Feedback Shield, prompt issue resolution"],
                ["Response rate", "Medium — confirmed Google signal", "Respond to 100% of reviews within 48hrs"],
                ["Keyword mentions", "Medium — affects relevance score", "Encourage specific service/location mentions"],
            ],
        }},
        { type: "h2", text: "The Compounding Effect" },
        { type: "p", text: "Here's what makes review management so powerful: the effects compound. More reviews → higher ranking → more visibility → more customers → more reviews. Every new review you collect makes the next one slightly easier to earn because more people are finding you." },
        { type: "p", text: "Conversely, falling behind on review velocity allows competitors to compound past you. A competitor who consistently gets 15 reviews/month while you get 2 will overtake your ranking position within 6–12 months, even if you started ahead." },
        { type: "cta", ctaLabel: "Start automating your review collection with Zyene →", ctaHref: "/signup" },
    ],
};
