/**
 * Blog posts — Month 1 (posts 1–4).
 * Google Reviews Basics + Competitor Analysis.
 */

import type { BlogPost } from "./blog-types";

export const post1: BlogPost = {
    slug: "how-to-get-50-google-reviews-in-30-days",
    title: "How to Get 50 Google Reviews in 30 Days",
    excerpt: "Most local businesses collect 1–2 reviews per month. Here's the exact 30-day playbook to get 50 — with scripts, timing, and automation strategies.",
    pillar: "google-reviews",
    pillarLabel: "Google Reviews",
    publishedAt: "2026-03-10",
    readMinutes: 8,
    author: { name: "Zyene Team", role: "Growth & SEO" },
    metaTitle: "How to Get 50 Google Reviews in 30 Days",
    metaDescription: "A step-by-step playbook for getting 50 Google reviews in 30 days. Includes exact request scripts, timing strategy, SMS vs email benchmarks, and automation tips.",
    keywords: ["how to get more google reviews", "get 50 google reviews", "google review strategy", "review request strategy"],
    relatedSlugs: ["why-google-reviews-matter-in-2026", "how-reviews-impact-local-map-pack-ranking"],
    internalLinks: [
        { label: "See how Zyene automates review requests", href: "/features" },
        { label: "Try Zyene free for 7 days", href: "/signup" },
    ],
    body: [
        { type: "p", text: "Most local businesses accumulate reviews the same way — by accident. A happy customer happens to leave one. You get 1 or 2 a month if you're lucky. At that pace, reaching 50 reviews takes 2–4 years." },
        { type: "p", text: "But 50 reviews isn't just a vanity milestone. It's the threshold where Google's local ranking algorithm starts giving your business significantly more prominence in map searches. Below it, you're competing with one hand tied behind your back." },
        { type: "p", text: "Here is a proven, 30-day playbook to get from wherever you are today to 50 reviews — without gaming the system, without fake reviews, and without annoying your customers." },
        { type: "h2", text: "Why 50 Reviews Is a Threshold, Not Just a Number" },
        { type: "p", text: "Google uses three primary factors to rank local businesses in Maps: Relevance, Proximity, and Prominence. Reviews — their quantity, recency, and the presence of owner responses — directly feed into Prominence. Businesses with 50+ reviews typically appear in local 3-pack results at a significantly higher rate than businesses with fewer than 20." },
        { type: "p", text: "Beyond ranking, consumer behavior shifts dramatically around review count. Studies show that trust peaks at around 40–50 reviews and plateaus after 100. A business with 50 fresh reviews is perceived as credible by the large majority of consumers — similar to one with 500 reviews." },
        { type: "h2", text: "The Real Reason You Don't Have 50 Reviews Yet" },
        { type: "p", text: "It's not that your customers are unhappy. It's that you're not asking. Research consistently shows that 70–80% of customers who have a positive experience will leave a review if asked — but fewer than 1 in 3 businesses have a systematic process for asking." },
        { type: "tip", text: "The best time to ask for a review is within 1–3 hours of a positive interaction — when the experience is fresh, the customer's satisfaction is highest, and they haven't mentally moved on to the next thing." },
        { type: "h2", text: "The 30-Day Playbook" },
        { type: "h3", text: "Week 1: Build Your Ask Infrastructure" },
        { type: "ol", items: [
            "Generate your Google review link: Go to your Google Business Profile, click 'Share review form', and copy the direct link. This is the URL you'll use in all your requests.",
            "Create a review request shortlink: Use a URL shortener or your own domain (e.g., yoursite.com/review) so the link looks clean in SMS messages.",
            "Draft your request scripts: Write one for SMS (under 160 characters) and one for email (3–5 sentences max). See scripts below.",
            "Identify your 'ask moments': The specific touchpoints in your customer journey when asking feels natural — checkout, job completion, appointment end.",
        ]},
        { type: "h3", text: "Week 2–4: Execute the Ask at Scale" },
        { type: "ol", items: [
            "Go back 90 days: Export your customer list from your POS, booking system, or CRM. Anyone who did business with you in the last 90 days is a warm candidate. Send them a one-time review request batch.",
            "Ask every new customer going forward: Make the review request part of your standard checkout or follow-up process. Every transaction, every day.",
            "Follow up once (and only once): If a customer doesn't respond in 5–7 days, send one follow-up. Don't send more — it damages the relationship.",
            "Respond to every review you receive: This signals to Google that you're active and encourages more reviews. It also shows new visitors that you care.",
        ]},
        { type: "h2", text: "Exact Request Scripts" },
        { type: "h3", text: "SMS Script (157 characters)" },
        { type: "quote", text: "Hi [Name], thanks for visiting [Business Name] today! We'd love a quick Google review — it really helps us grow: [your-review-link] Thank you! 🙏" },
        { type: "h3", text: "Email Script" },
        { type: "quote", text: "Subject: Quick favor from [Business Name]\n\nHi [Name],\n\nThank you for your visit — it was great to see you. If you have 60 seconds, a Google review would mean the world to us and help other [customers/patients/clients] find us.\n\n→ Leave a review here: [your-review-link]\n\nThank you!\n[Your Name]" },
        { type: "h2", text: "SMS vs. Email: Response Rate Benchmarks" },
        { type: "table", table: {
            headers: ["Channel", "Open Rate", "Review Conversion Rate", "Best For"],
            rows: [
                ["SMS", "98%", "15–25%", "Service businesses, retail, restaurants"],
                ["Email", "22–28%", "5–10%", "Healthcare, B2B, post-purchase"],
                ["Both (SMS + email follow-up)", "—", "20–30%", "Maximum results"],
            ],
        }},
        { type: "h2", text: "How to Hit 50 in 30 Days Mathematically" },
        { type: "p", text: "If you serve 10 customers per day (300/month) and send 80% of them a review request, that's 240 requests. At a 20% conversion rate, that's 48 new reviews. Add your 90-day backfill batch, and you're past 50." },
        { type: "p", text: "Businesses with fewer daily customers need to be more aggressive with the backfill. If you serve 3 customers/day, go back 6 months for your initial batch to build the critical mass." },
        { type: "tip", text: "Never offer discounts or rewards in exchange for reviews. Google's policies prohibit review gating and incentivized reviews. The good news: you don't need to. Simply asking — professionally and at the right time — is enough." },
        { type: "h2", text: "Automate It So You Never Miss an Ask" },
        { type: "p", text: "The businesses that consistently grow their review count are the ones who have automated the ask. Manually texting every customer doesn't scale, and you'll stop doing it when things get busy." },
        { type: "p", text: "Tools like Zyene connect to your workflow (via Zapier, Square, or direct API) and send review requests automatically at the right moment — without any manual effort. You set it up once and it works every day, for every customer." },
        { type: "cta", ctaLabel: "See how Zyene automates review requests →", ctaHref: "/features" },
        { type: "h2", text: "What to Expect" },
        { type: "p", text: "In the first 30 days with a systematic ask process, most businesses see 3–5× their previous monthly review rate. The exact number depends on your daily customer volume and how consistently you execute the ask." },
        { type: "p", text: "Once you cross 50 reviews, maintain momentum. Aim for at least 5–10 new reviews per month to keep your profile fresh — Google's algorithm weighs recency, not just total count." },
    ],
};

export const post2: BlogPost = {
    slug: "why-google-reviews-matter-in-2026",
    title: "Why Google Reviews Matter More Than Ever in 2026",
    excerpt: "Google Reviews have evolved from a nice-to-have into critical business infrastructure. Here's what changed in 2026 and why your review profile is now your most important marketing asset.",
    pillar: "google-reviews",
    pillarLabel: "Google Reviews",
    publishedAt: "2026-03-17",
    readMinutes: 7,
    author: { name: "Zyene Team", role: "Growth & SEO" },
    metaTitle: "Why Google Reviews Matter More Than Ever in 2026",
    metaDescription: "Google Reviews in 2026: how they impact local search rankings, AI Overviews, consumer trust, and revenue. A data-driven guide for local business owners.",
    keywords: ["why google reviews matter", "google reviews 2026", "google reviews local seo", "google reviews importance"],
    relatedSlugs: ["how-to-get-50-google-reviews-in-30-days", "how-reviews-impact-local-map-pack-ranking"],
    internalLinks: [
        { label: "Learn about Zyene's review monitoring", href: "/features" },
        { label: "See industry-specific strategies", href: "/industries" },
    ],
    body: [
        { type: "p", text: "In 2022, Google Reviews were a useful marketing tool. In 2024, they became a ranking factor. In 2026, they are business infrastructure — as fundamental as your phone number or your hours of operation. If you don't actively manage your Google review profile, you are actively losing customers." },
        { type: "p", text: "Here's what's changed and why it matters more now than it ever has." },
        { type: "h2", text: "Google Reviews Now Power AI Overviews" },
        { type: "p", text: "One of the biggest changes in 2025–2026 was the expansion of Google's AI Overviews for local search queries. When someone searches 'best Italian restaurant near me' or 'dentist in Austin TX', Google's AI synthesizes information from multiple sources — and Google Reviews are among the most heavily weighted inputs." },
        { type: "p", text: "Businesses with more reviews, higher ratings, and active owner responses are significantly more likely to appear in AI Overview summaries. This is free, high-visibility placement at the very top of the search results page — but it's only accessible to businesses with strong review profiles." },
        { type: "h2", text: "The Local 3-Pack: Your Revenue Engine" },
        { type: "p", text: "Google Maps' Local 3-Pack — the three business results that appear with a map in local search results — captures 44% of all clicks on local search result pages. Being in the 3-pack for your primary keywords is worth more than any paid ad campaign for most local businesses." },
        { type: "p", text: "Google uses three factors to determine 3-pack rankings: Relevance (does your business match what they searched?), Proximity (how close are you?), and Prominence (how well-known and well-reviewed are you?). Reviews directly impact Prominence — and unlike Proximity, which you can't control, Prominence is entirely within your influence." },
        { type: "tip", text: "A business with 80 reviews and a 4.6-star rating will typically outrank a closer competitor with 15 reviews and a 4.8-star rating in Google Maps. Review quantity matters as much as quality — up to a point." },
        { type: "h2", text: "Consumer Psychology: The Numbers Behind Reviews" },
        { type: "table", table: {
            headers: ["Stat", "Source / Context"],
            rows: [
                ["93% of consumers read reviews before visiting a local business", "BrightLocal Local Consumer Review Survey"],
                ["88% of consumers trust online reviews as much as personal recommendations", "BrightLocal"],
                ["A 1-star increase on Yelp leads to a 5–9% revenue increase", "Harvard Business School"],
                ["53% of customers expect businesses to reply to reviews within a week", "ReviewTrackers"],
                ["Only 13% of consumers will use a business with a 1–2 star rating", "BrightLocal"],
                ["Reviews are the #1 local ranking factor in the Google Maps 3-pack", "Whitespark Local Ranking Factors"],
            ],
        }},
        { type: "h2", text: "The Trust Gap: New vs. Established Businesses" },
        { type: "p", text: "One of the most underappreciated advantages of reviews is that they level the playing field between new businesses and established ones. A 2-year-old restaurant with 200 Google reviews can outcompete a 20-year-old institution with 30 reviews in terms of new customer acquisition." },
        { type: "p", text: "At the same time, this creates an urgent problem for new businesses: until you've built a review base, you're invisible to the majority of potential customers who are searching online. The faster you build your review profile, the faster you close the trust gap." },
        { type: "h2", text: "Review Recency: Google's Freshness Signal" },
        { type: "p", text: "Having 200 reviews that are all 3 years old is less valuable than having 80 reviews with 30 in the last 90 days. Google's algorithm gives extra weight to recent reviews because they reflect the current state of your business — and because active businesses with new reviews signal to Google that they're worth promoting." },
        { type: "p", text: "This is why review management isn't a 'get to 50 and stop' project. It's an ongoing operation. Aim for a minimum of 5–10 new reviews per month to maintain freshness." },
        { type: "h2", text: "Response Rate: The Overlooked Ranking Signal" },
        { type: "p", text: "Google has confirmed that responding to reviews is a signal in their local ranking algorithm. A business that responds to 80% of its reviews is seen as more engaged and trustworthy than one that never responds — even if the number of reviews is similar." },
        { type: "p", text: "Beyond the algorithmic benefit, responses serve a practical purpose: they're public messages that show potential customers how you handle feedback. A gracious, specific response to a 3-star review often does more to convert a hesitant visitor than five more 5-star reviews." },
        { type: "tip", text: "Aim to respond to 100% of your reviews — positive and negative. For 5-star reviews, a short thank-you that mentions a specific detail is better than a generic 'Thanks for the 5 stars!'. For negative reviews, the 3-part framework works best: Acknowledge, Apologize, Offer to resolve." },
        { type: "h2", text: "What This Means for Your Business Today" },
        { type: "p", text: "If you're not actively collecting reviews, responding to all of them, and monitoring your rating across platforms, you are losing customers every day to competitors who are. This isn't a marketing nice-to-have — it's table stakes for local business survival in 2026." },
        { type: "p", text: "The good news: with the right tools and a consistent process, building and maintaining a strong review profile is a 20–30 minute per week activity, not a full-time job." },
        { type: "cta", ctaLabel: "See how Zyene manages your entire review profile →", ctaHref: "/features" },
    ],
};

export const post3: BlogPost = {
    slug: "birdeye-pricing-breakdown-2026",
    title: "Birdeye Pricing Breakdown: Is It Worth $299/mo for Local Businesses?",
    excerpt: "Birdeye's pricing page is intentionally vague. We break down exactly what you pay, what you get, who it's actually built for — and whether local business owners should be paying it.",
    pillar: "competitor-analysis",
    pillarLabel: "Competitor Analysis",
    publishedAt: "2026-03-24",
    readMinutes: 9,
    author: { name: "Zyene Team", role: "Growth & SEO" },
    metaTitle: "Birdeye Pricing Breakdown 2026: Is It Worth $299/mo?",
    metaDescription: "Full Birdeye pricing breakdown for 2026. What you actually pay, what's included, what's an add-on, and whether Birdeye is worth it for your local business.",
    keywords: ["birdeye pricing", "birdeye cost", "birdeye pricing 2026", "how much does birdeye cost", "birdeye review"],
    relatedSlugs: ["birdeye-alternatives-for-local-businesses"],
    internalLinks: [
        { label: "Compare Zyene vs Birdeye", href: "/compare/birdeye" },
        { label: "See Zyene pricing", href: "/pricing" },
    ],
    body: [
        { type: "p", text: "Birdeye is one of the best-known names in reputation management. They've been around since 2012, have over 100,000 customers, and have raised hundreds of millions in venture capital. They're also one of the most expensive options in the market — and their pricing page makes it deliberately difficult to understand what you'll actually pay." },
        { type: "p", text: "This breakdown is for local business owners who are considering Birdeye, currently paying for Birdeye, or looking to understand whether the price is justified." },
        { type: "h2", text: "The Headline: What Birdeye Actually Costs" },
        { type: "p", text: "Birdeye's published starting price is $299/month, billed annually. That means you're committing to $3,588 per year minimum — before any add-ons or per-location fees." },
        { type: "p", text: "In practice, most local businesses end up paying significantly more. Birdeye uses a tiered pricing structure that gates many features behind higher plans. AI reply features, competitor tracking, and API access are typically only available on mid-to-upper tiers, which can push the effective price to $400–$600/month per location for a full-featured setup." },
        { type: "warning", text: "Birdeye requires an annual contract. If your business circumstances change — you close a location, your needs shift, or you find a better option — you're locked in for the year. There are no published month-to-month options." },
        { type: "h2", text: "What You Actually Get at Each Tier" },
        { type: "table", table: {
            headers: ["Feature", "Starter (~$299/mo)", "Growth (~$399/mo)", "Dominate (~$499+/mo)"],
            rows: [
                ["Review monitoring", "✓", "✓", "✓"],
                ["Review requests (SMS/email)", "✓", "✓", "✓"],
                ["AI reply suggestions", "Limited", "✓", "✓"],
                ["Competitor tracking", "✗", "Limited", "✓"],
                ["REST API access", "✗", "✗", "✓"],
                ["Webchat", "✗", "✓", "✓"],
                ["Tickets/surveys", "✗", "✓", "✓"],
                ["Dedicated success manager", "✗", "✗", "✓"],
            ],
        }},
        { type: "p", text: "Note: Birdeye's tier names and inclusions change frequently. This table reflects general tier positioning based on publicly available information as of 2026. Actual contracts may vary — always request a detailed feature list before signing." },
        { type: "h2", text: "The Hidden Costs Most People Don't Anticipate" },
        { type: "ul", items: [
            "Per-location pricing: Multi-location businesses pay per location. At 3 locations on a $299 plan, you're at $897/month before you've accessed any premium features.",
            "Onboarding fees: Many Birdeye contracts include a one-time onboarding fee of $200–$500 that isn't mentioned on the pricing page.",
            "Contract renewal: Birdeye auto-renews annual contracts. If you don't cancel within the notice period (often 30–60 days before renewal), you're locked in for another year.",
            "Add-on costs: Features like advanced surveys, referral programs, and Birdeye Payments are add-ons beyond the base tier pricing.",
        ]},
        { type: "h2", text: "Who Birdeye Is Actually Built For" },
        { type: "p", text: "To be fair to Birdeye: at scale, the platform offers capabilities that go well beyond review management. It's a full customer experience platform with messaging, ticketing, payments, and surveys. For enterprise businesses managing 20+ locations with a dedicated CX team, the price may be entirely justified." },
        { type: "p", text: "But the vast majority of Birdeye's marketing targets small-to-medium local businesses — the $50k–$500k revenue businesses that are most price-sensitive and least likely to need enterprise CX infrastructure." },
        { type: "h2", text: "The Value Question: What Are You Actually Getting?" },
        { type: "p", text: "The core use case for most local businesses in Birdeye is review monitoring, review request automation, and AI reply suggestions. These three features are the reason 80%+ of local business customers sign up." },
        { type: "p", text: "Those exact three features — plus the Negative Feedback Shield, competitor tracking, and GBP keyword performance — are available in Zyene's Starter plan at $29.99/month. No annual contract." },
        { type: "h2", text: "The Bottom Line" },
        { type: "p", text: "Birdeye is a credible, capable platform — for the right customer. If you're a franchise with 50+ locations, need an enterprise CX suite, and have a team to manage it, Birdeye is worth evaluating seriously." },
        { type: "p", text: "If you're a local business owner managing 1–5 locations who primarily needs to grow your Google reviews, respond with AI, and protect your reputation, you're likely paying 10× more than you need to. The core features you use are available at a fraction of the price elsewhere." },
        { type: "cta", ctaLabel: "See the full Zyene vs Birdeye comparison →", ctaHref: "/compare/birdeye" },
    ],
};

export const post4: BlogPost = {
    slug: "birdeye-alternatives-for-local-businesses",
    title: "5 Cheaper Birdeye Alternatives for Local Businesses (2026)",
    excerpt: "Paying $299+/mo for Birdeye? Here are 5 alternatives that give you review management, AI replies, and reputation protection at a fraction of the price.",
    pillar: "competitor-analysis",
    pillarLabel: "Competitor Analysis",
    publishedAt: "2026-03-31",
    readMinutes: 10,
    author: { name: "Zyene Team", role: "Growth & SEO" },
    metaTitle: "5 Cheaper Birdeye Alternatives for Local Businesses (2026)",
    metaDescription: "The 5 best Birdeye alternatives for local businesses in 2026. Compare pricing, features, and fit for owner-operators looking for affordable review management.",
    keywords: ["birdeye alternatives", "cheaper than birdeye", "birdeye alternative 2026", "best review management software", "birdeye competitors"],
    relatedSlugs: ["birdeye-pricing-breakdown-2026"],
    internalLinks: [
        { label: "Compare Zyene vs Birdeye in detail", href: "/compare/birdeye" },
        { label: "Start Zyene free for 7 days", href: "/signup" },
    ],
    body: [
        { type: "p", text: "Birdeye dominates the reputation management space in brand recognition, but it's priced for enterprise clients — starting at $299/month with an annual contract. For the vast majority of local business owners, that pricing is simply not justified by the features they'll actually use." },
        { type: "p", text: "These are the 5 best alternatives to Birdeye in 2026, evaluated across three criteria: price, core feature coverage, and fit for owner-operators." },
        { type: "h2", text: "1. Zyene Reviews — Best Overall for Local Businesses" },
        { type: "p", text: "Zyene is purpose-built for local business owners who need the core review management features without enterprise pricing or annual contracts. It covers every major feature local businesses use Birdeye for — and adds capabilities Birdeye doesn't have." },
        { type: "ul", items: [
            "Price: $29.99/mo (Starter, 1 location) — 10× cheaper than Birdeye's starting price",
            "Review monitoring: Google, Facebook, Yelp — real-time alerts",
            "AI reply suggestions: Unlimited on all plans (Birdeye gates this)",
            "Auto-commenter: Hands-free AI replies to 4+5-star reviews",
            "Negative Feedback Shield: Route unhappy customers to private resolution (Birdeye doesn't have this)",
            "Competitor tracking: Monitor up to 10 nearby competitors",
            "GBP keyword performance dashboard",
            "Full REST API on all paid plans",
            "No annual contract — cancel anytime",
            "7-day free trial with full access",
        ]},
        { type: "tip", text: "Zyene's Negative Feedback Shield is a unique feature not found in Birdeye. It intercepts unhappy customers before they post publicly and routes them to a private resolution — protecting your Google rating from avoidable 1-star reviews." },
        { type: "h2", text: "2. NiceJob — Best for Simplicity" },
        { type: "p", text: "NiceJob is a simpler, more visual platform focused primarily on automating review collection. It's well-suited for home services businesses that want a clean interface and basic review automation without a lot of configuration." },
        { type: "ul", items: [
            "Price: $75/mo (Grow plan) — 4× cheaper than Birdeye",
            "Review monitoring and SMS/email requests: ✓",
            "AI reply suggestions: ✗ (not available in NiceJob)",
            "Competitor tracking: ✗",
            "Negative Feedback Shield equivalent: Basic",
            "Website builder: Available on Convert plan (+$100/mo)",
            "No annual contract",
        ]},
        { type: "h2", text: "3. GatherUp — Best for Survey-Focused Businesses" },
        { type: "p", text: "GatherUp has strong survey and NPS capabilities alongside review collection. It's a good fit for businesses that need customer satisfaction measurement beyond just reviews — healthcare practices, service franchises, and multi-location chains." },
        { type: "ul", items: [
            "Price: $99/mo per location — 3× cheaper than Birdeye",
            "Review monitoring and SMS/email requests: ✓",
            "Customer surveys and NPS: ✓ (core strength)",
            "AI reply suggestions: Limited",
            "Competitor tracking: ✗",
            "White-label for agencies: ✓",
            "No annual contract",
        ]},
        { type: "h2", text: "4. Podium — Best for Businesses That Need Messaging + Reviews" },
        { type: "p", text: "Podium is less a Birdeye alternative and more a different category of tool. It's a customer messaging and payments platform that includes review management as one component. If you need SMS inbox, two-way customer messaging, and payments via text in addition to reviews, Podium is worth considering." },
        { type: "ul", items: [
            "Price: $399/mo — actually more expensive than Birdeye for base tier",
            "Two-way SMS messaging: ✓ (core differentiator)",
            "Payments via text: ✓",
            "Review management: ✓ but reviews-focused tools are secondary",
            "AI reply suggestions: Basic",
            "Annual contract required",
        ]},
        { type: "warning", text: "If your primary need is review management and reputation, Podium is not the right tool. It's a messaging platform first. You'll pay $399+/mo for a lot of features you won't use." },
        { type: "h2", text: "5. Reputation.com — Best for Large Enterprises Wanting to Leave Birdeye" },
        { type: "p", text: "Reputation.com (now Reputation) is an enterprise-grade platform comparable to Birdeye in scope and target market. If you're on Birdeye and outgrowing it — managing 50+ locations with complex enterprise needs — Reputation.com is a credible alternative at the same tier. For local businesses, it's not appropriate." },
        { type: "h2", text: "The Comparison Table" },
        { type: "table", table: {
            headers: ["Platform", "Starting Price", "AI Replies", "Competitor Tracking", "No Contract", "Best For"],
            rows: [
                ["Zyene Reviews", "$29.99/mo", "✓ Unlimited", "✓", "✓", "Local business owners, 1–5 locations"],
                ["NiceJob", "$75/mo", "✗", "✗", "✓", "Simple review collection, home services"],
                ["GatherUp", "$99/mo per location", "Limited", "✗", "✓", "NPS + reviews, healthcare"],
                ["Podium", "$399/mo", "Basic", "✗", "✗", "Messaging + payments + reviews"],
                ["Birdeye", "$299/mo", "Higher tiers", "Premium only", "✗", "Enterprise, 20+ locations"],
            ],
        }},
        { type: "h2", text: "The Verdict" },
        { type: "p", text: "For local business owners — restaurants, dental practices, auto repair shops, salons, home services — the majority of Birdeye's pricing is spent on enterprise infrastructure you'll never use. The core features that matter for local businesses: review monitoring, AI replies, automated requests, and a shield against bad reviews — are available for $30–$100/month." },
        { type: "p", text: "If you're currently paying $299+/month for Birdeye and primarily using it for reviews, you have a real opportunity to reinvest that $2,400+/year into your business." },
        { type: "cta", ctaLabel: "Try Zyene free for 7 days — no credit card lock-in →", ctaHref: "/signup" },
    ],
};
