export const CATEGORY_FALLBACK_EMOJI: Record<string, string> = {
    restaurant: "🍽️",
    ice_cream: "🍦",
    cafe: "☕",
    bar: "🍸",
    salon: "💇",
    spa: "💆",
    gym: "🏋️",
    fitness: "💪",
    medical: "🏥",
    dental: "🦷",
    retail: "🛍️",
    auto: "🚗",
    hotel: "🛏️",
    service: "🛠️",
    smoke: "🌿",
    other: "⭐",
};

/** Normalized label → emoji for common owner-entered plain-text tags */
export const LABEL_EMOJI_MAP: Record<string, string> = {
    professional: "👔",
    friendly: "🤝",
    cleanliness: "🧹",
    clean: "🧹",
    "before & after photos": "📸",
    "before and after photos": "📸",
    "healthier home": "🏠",
    "fast & reliable": "⚡",
    "fast and reliable": "⚡",
    "fast service": "⚡",
    speed: "⚡",
    timeliness: "⏰",
    "wait time": "⏰",
    quality: "⭐",
    service: "👨‍💼",
    staff: "👥",
    communication: "💬",
    value: "💰",
    prices: "💰",
    price: "💰",
    ambiance: "✨",
    atmosphere: "✨",
    food: "🍽️",
    flavor: "🍦",
    taste: "🍦",
    "mix-ins": "🧁",
    "mix ins": "🧁",
    "made fresh": "❄️",
    scoops: "🍨",
    size: "🍨",
    expertise: "🧠",
    honesty: "🤝",
    selection: "🛍️",
    experience: "🎯",
    care: "❤️",
    comfort: "😌",
    skill: "✨",
    equipment: "🏋️",
    trainers: "👨‍🏫",
    room: "🛏️",
    location: "📍",
    portions: "🍕",
    drinks: "🍸",
    coffee: "☕",
};
