import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { emailPreviews } from "../tests/fixtures/email-previews";
import { escapeHtml } from "@/lib/security/html-escape";

const folder = resolve("output/email-audit");
mkdirSync(folder, { recursive: true });
const previews = emailPreviews();
writeFileSync(resolve(folder, "auth-templates.json"), JSON.stringify(previews.filter(p => p.authSource).map(p => ({ slug: p.id.slice(5), subject: p.subject, html: p.authSource })), null, 2));
for (const preview of previews) {
    writeFileSync(resolve(folder, `${preview.id}.html`), preview.html);
    if (preview.authSource) writeFileSync(resolve(folder, `${preview.id}-source.html`), preview.authSource);
    writeFileSync(resolve(folder, `${preview.id}-edit.html`), `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>${preview.id} email source</title></head><body><h1>${preview.id}</h1><label>Subject <input aria-label="Email subject" value="${escapeHtml(preview.subject ?? preview.id)}"></label><label>Source<textarea aria-label="Email source" style="display:block;width:95%;height:70vh;">${escapeHtml(preview.authSource ?? preview.html)}</textarea></label></body></html>`);
}
writeFileSync(resolve(folder, "index.html"), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Email audit previews</title><style>body{font:16px Arial;max-width:900px;margin:32px auto;padding:0 20px;color:#18181b}li{margin:20px 0;line-height:1.6}.shots{font-size:14px}a{color:#1a0dab}</style></head><body><h1>Email audit previews</h1><p>${previews.length} templates and variants. These use synthetic customer data.</p><p>Open a live preview or inspect captured phone/laptop screenshots. Screenshots are generated by <code>pnpm test:email</code>.</p><ul>${previews.map(p => `<li><a href="${p.id}.html">${p.id}</a> · <a href="${p.id}-edit.html">Source</a><br><span class="shots">${[[375, "Phone"], [1366, "Laptop"]].map(([width, label]) => ["light", "dark"].map(mode => `<a href="screenshots/${p.id}-${width}-${mode}.png">${label} ${mode}</a>`).join(" · ")).join(" · ")}</span></li>`).join("")}</ul></body></html>`);
console.log(`Rendered ${previews.length} previews in ${folder}`);
