import type { PublicProfileBusinessRecord, PublicProfilePreviewValues } from "@/types/components";

export function buildPublicReviewFlowPreviewProps(
    business: PublicProfileBusinessRecord,
    previewState: PublicProfilePreviewValues,
    previewStep: "rating" | "tags" | "generating" | "review" | "thankyou" | "negative",
) {
    return {
        businessId: business.id,
        businessName: business.name,
        businessCategory: business.category || "",
        brandColor: previewState.brand_color,
        reviewPageBackgroundColor: previewState.review_page_background_color,
        logoUrl: previewState.logo_url ?? undefined,
        minStars: previewState.min_stars_for_google,
        ratingStyle: previewState.rating_style,
        welcomeMsg: previewState.welcome_message,
        apologyMsg: previewState.apology_message,
        ratingSubtitle: previewState.rating_subtitle,
        tagsHeading: previewState.tags_heading,
        tagsSubheading: previewState.tags_subheading,
        customTags: previewState.custom_tags ?? undefined,
        enableStaffSelection: previewState.enable_staff_selection,
        staffNames: previewState.staff_names,
        googleHeading: previewState.google_heading,
        googleSubheading: previewState.google_subheading,
        googleButtonText: previewState.google_button_text,
        googleUrl: previewState.google_review_url,
        negativeSubheading: previewState.negative_subheading,
        negativeTextareaPlaceholder: previewState.negative_textarea_placeholder,
        negativeButtonText: previewState.negative_button_text,
        privateFeedbackEmailMode: previewState.private_feedback_email_mode,
        privateFeedbackPhoneMode: previewState.private_feedback_phone_mode,
        privateFeedbackOfferMode: previewState.private_feedback_offer_mode,
        privateFeedbackOfferMessage: previewState.private_feedback_offer_message,
        thankYouHeading: previewState.thank_you_heading,
        thankYouMessage: previewState.thank_you_message,
        footerText: previewState.footer_text,
        footerCompanyName: previewState.footer_company_name,
        footerLink: previewState.footer_link,
        footerLogoUrl: previewState.footer_logo_url ?? undefined,
        hideBranding: previewState.hide_branding,
        isPreview: true as const,
        previewStep,
        className: "min-h-full w-full rounded-[2rem]",
    };
}
