import type { ContentFormValues } from "@/components/settings/review-content-schema";
import {
    DEFAULT_REVIEW_FOOTER_COMPANY_NAME,
    DEFAULT_REVIEW_FOOTER_LINK,
    DEFAULT_REVIEW_FOOTER_LOGO_URL,
    DEFAULT_REVIEW_FOOTER_TEXT,
} from "@/lib/brand/review-flow-footer-branding";

export const reviewContentFormDefaults: ContentFormValues = {
    min_stars_for_google: 4,
    google_review_url: "",
    rating_subtitle: "",
    tags_heading: "",
    tags_subheading: "",
    enable_staff_selection: false,
    staff_names: "",
    google_heading: "",
    google_subheading: "",
    google_button_text: "",
    negative_subheading: "",
    negative_textarea_placeholder: "",
    negative_button_text: "",
    private_feedback_email_mode: "optional",
    private_feedback_phone_mode: "hidden",
    private_feedback_offer_mode: "hidden",
    private_feedback_offer_message: "",
    thank_you_heading: "",
    thank_you_message: "",
    footer_text: DEFAULT_REVIEW_FOOTER_TEXT,
    footer_company_name: DEFAULT_REVIEW_FOOTER_COMPANY_NAME,
    footer_link: DEFAULT_REVIEW_FOOTER_LINK,
    footer_logo_url: DEFAULT_REVIEW_FOOTER_LOGO_URL,
    hide_branding: false,
    welcome_message: "",
    apology_message: "",
    rating_style: "emoji",
};
