import type { ContentFormValues } from "@/components/settings/review-content-schema";

export const reviewContentFormDefaults: ContentFormValues = {
    min_stars_for_google: 4,
    google_review_url: "",
    rating_subtitle: "",
    tags_heading: "",
    tags_subheading: "",
    enable_staff_selection: false,
    staff_names: "",
    google_heading: "",
    google_subheading: "",
    google_button_text: "",
    negative_subheading: "",
    negative_textarea_placeholder: "",
    negative_button_text: "",
    private_feedback_email_mode: "optional",
    private_feedback_phone_mode: "hidden",
    private_feedback_offer_mode: "hidden",
    private_feedback_offer_message: "",
    thank_you_heading: "",
    thank_you_message: "",
    footer_text: "",
    footer_company_name: "Zyene",
    footer_link: "https://zyene.com",
    footer_logo_url: "/zyene-footer.png",
    hide_branding: false,
    welcome_message: "",
    apology_message: "",
    rating_style: "emoji",
};
